server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "fX8Dg8bnZah9vzS0mM0gJz2RRnMOgx4OSesxfzOg3p4fsXVu0Ceh8d62zTayfZyk\n"
  valid-duration: 3600
  refreshable-duration: 36000 #in second