server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/identity_service'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "fX8Dg8bnZah9vzS0mM0gJz2RRnMOgx4OSesxfzOg3p4fsXVu0Ceh8d62zTayfZyk\n"
  valid-duration: 3600
  refreshable-duration: 360000 #in second